wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.2
    start_time: 1630340787
    t:
      3:
      - 2
      4: 3.8.2
      5: 0.12.1
      8:
      - 5
